version: '2'

services:
  db:
    image: mysql/mysql-server:5.7
    container_name: db
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    
    volumes:
      - /docker/mysql/beta/initdb:/docker-entrypoint-initdb.d
      - /docker/mysql/beta/config/my.cnf:/etc/my.cnf
      - /docker/mysql/beta/data:/var/lib/mysql
  webapi:
    image: ljqtestapp-webapi
    container_name: webapi
    ports:
      - 8001:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /docker/aspnetcore/config/appsettings.json:/appsettings.json     
    depends_on:
      - db
  